apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://ims-prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    url: http://ims-loki:3100
    access: proxy
    editable: true

  - name: Jaeger
    type: jaeger
    url: http://ims-jaeger:16686
    access: proxy
    editable: true
